# Generated by Django 3.1.1 on 2020-11-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flat_no', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=12)),
                ('age', models.IntegerField(default=None)),
                ('profession', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('marig_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20)),
            ],
        ),
    ]
